/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sisproducao.view;

/**
 *
 * @author ritacosta
 */
public class SisProducao extends javax.swing.JFrame {

    /**
     * Creates new form SisProducao
     */
    public SisProducao() {
        initComponents();
    }

    public void abrirCadPrestador() {
        CadastroPrestador cad_pres = new CadastroPrestador();
        cad_pres.setVisible(true);
        
    }

    public void abrirCadProcedimento() {
        CadastroProcedimento cad_pro = new CadastroProcedimento();
        cad_pro.setVisible(true);
    }

    public void abrirCadProfissional() {
        CadastroProfissional cad_prof = new CadastroProfissional();
        cad_prof.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmiCadastroPrestador = new javax.swing.JMenuItem();
        jmiCadastroProcedimento = new javax.swing.JMenuItem();
        jmiCadastroProfissional = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Produção - CMR");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        jMenu1.setText("Início");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastros");

        jmiCadastroPrestador.setText("Cadastro Prestador");
        jmiCadastroPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroPrestadorActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCadastroPrestador);

        jmiCadastroProcedimento.setText("Cadastro Procedimento");
        jmiCadastroProcedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroProcedimentoActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCadastroProcedimento);

        jmiCadastroProfissional.setText("Cadastro Profissional");
        jmiCadastroProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroProfissionalActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCadastroProfissional);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCadastroPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroPrestadorActionPerformed
        abrirCadPrestador();
    }//GEN-LAST:event_jmiCadastroPrestadorActionPerformed

    private void jmiCadastroProcedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroProcedimentoActionPerformed
        abrirCadProcedimento();
    }//GEN-LAST:event_jmiCadastroProcedimentoActionPerformed

    private void jmiCadastroProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroProfissionalActionPerformed
        abrirCadProfissional();
    }//GEN-LAST:event_jmiCadastroProfissionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SisProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SisProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SisProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SisProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SisProducao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmiCadastroPrestador;
    private javax.swing.JMenuItem jmiCadastroProcedimento;
    private javax.swing.JMenuItem jmiCadastroProfissional;
    // End of variables declaration//GEN-END:variables
}
